name: "auto-context"
on:
  schedule:
  # Update context.tf nightly
  - cron:  '27 11 * * *'
  workflow_dispatch:

jobs:
  update:
    #if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
    - uses: cloudposse/github-action-terraform-auto-context@main
