name: chatops
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
  pull_request:
    types: [opened, synchronized, reopened]

jobs:
  tests-bats:
    # only run on pull requests so long as they don't come from forks
    if: ( (github.event_name == 'pull_request') && (github.event.pull_request.head.repo.full_name == github.repository) ) || (github.event_name != 'pull_request')
    runs-on: ubuntu-latest
    steps:
      - name: "Handle common commands and run tests"
        uses: cloudposse/github-action-terraform-ci@main
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
