name: chatops
on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  tests-bats:
    runs-on: ubuntu-latest
    steps:
      - name: "Handle common commands and run tests"
        uses: cloudposse/github-action-terraform-ci@4dc880e5c03b1ef8cbe66a17e0b4008c46e32f5a
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
