name: Debugging info
on:
  schedule:
  # Example of job definition:
  # .---------------- minute (0 - 59)
  # |  .------------- hour (0 - 23)
  # |  |  .---------- day of month (1 - 31)
  # |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
  # |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
  # |  |  |  |  |
  # *  *  *  *  * user-name command to be executed
  # Update README.md nightly at 4am UTC
  - cron: '0/5 * * * *'

jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
    - name: Print the context
      shell: bash
      env:
        JSON: ${{ toJSON(github) }}
      run: |
        printf "JSON representation of `github` available is:\n\n%s\n" "${JSON}"


