name: default-branch-test
on:
  push:
    branches:
    - $default-branch
    - main
    - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Parse
      shell: bash
      env:
        BV: $default-branch
        CID: ${{ github.event.client_payload.github.payload.comment.id }}
        JSON: ${{ toJSON(github.event.client_payload) }}
      run: |
        echo BV is "$BV"
        printf "CID is '%s'\n" "$CID"
        printf "JSON is: \n%s\n\n" "$JSON"
